USE master

--CREATE DATABASE QUAN LY NGAN HANG
GO 
CREATE DATABASE QLNH
--DROP DATABASE QLNH
GO
USE QLNH



-------------------TẠO BẢNG CHO CƠ SỞ DỮ LIỆU-------------------

--CCCD VÀ SDT NÊN SỬ DỤNG VARCHAR VÌ NÓ CÓ THỂ CHỨA KÝ TỰ BẮT ĐẦU BẰNG SỐ 0 CÒN KIỂU INT THÌ SẼ BỎ MẤT SỐ 0 Ở ĐẦU (VARCHAR:0384629483, INT:384629483)
GO
CREATE TABLE KHACHHANG(MAKH CHAR(10) NOT NULL,
						TENKH NVARCHAR(70),
						GIOITINH NVARCHAR,
						CCCD VARCHAR(12),
						SDT VARCHAR(10),
						EMAIL NVARCHAR(100),
						DIACHI NVARCHAR(100),
						QUOCTICH NVARCHAR(20),
						DOITUONG NVARCHAR,
						NGAYTAO DATETIME)
--VÍ DỤ(MAKH: KH001; TENKH: NGUYỄN THỊ C; GIOUITINH: NỮ; CCCD: 012345678912; SDT: 0123456789; EMAIL: NGUYENTHIC@GMAIL.COM; DIACHI: SỐ 7 HOÀNG HỮU NAM,THÀNH PHỐ THỦ ĐỨC, THÀNH PHỐ HỒ CHÍ MINH; QUOCTICH: VIỆT NAM; DOITUONG: CÁ NHÂN; NGAYTAO: 5/5/2015)

GO
CREATE TABLE LOAITAIKHOAN(MALOAITK VARCHAR(10) NOT NULL,
							CHITIET NVARCHAR(30))
--VÍ DỤ(MALOAITK: LOAITK01; CHITIET: TIẾT KIỆM)

GO
CREATE TABLE LOAITIEN(MALOAITIEN VARCHAR(10) NOT NULL,
						TENLOAITIEN NVARCHAR(50),
						KYHIEU NVARCHAR,
						QUOCGIA NVARCHAR,
						TRANGTHAI NVARCHAR)
--VÍ DỤ(MALOAITIEN: VND, VIỆT NAM ĐỒNG, đ, VIỆT NAM, HOATDONG)

GO
CREATE TABLE TAIKHOAN(MATK CHAR(10) NOT NULL,
							MAKH CHAR(10),
							SOTAIKHOAN VARCHAR,
							MALOAITK VARCHAR(10),
							SODU DECIMAL,
							MALOAITIEN VARCHAR(10),
							NGAYMOTK DATETIME,
							TRANGTHAI NVARCHAR)
--VÍ DỤ(MATK: TK001; MAKH: KH001, SOTAIKHOAN: 0917253; MALOAITK: LOAITK01; SODU: 7500000; MALOAITIEN: VND; NGAYMOTK: 4/12/2018; TRANGTHAI: MỞ)



-------------------RÀNG BUỘC KHÓA CHÍNH-------------------

---KHÓA CHÍNH CHO BẢNG KHÁCH HÀNG---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KH PRIMARY KEY(MAKH)

---KHÓA CHÍNH CHO BẢNG LOẠI TÀI KHOẢN---
GO
ALTER TABLE LOAITAIKHOAN
ADD CONSTRAINT PK_LTK PRIMARY KEY(MALOAITK)

--KHÓA CHÍNH CHO BẢNG LOẠI TIỀN TỆ---
GO
ALTER TABLE LOAITIEN
ADD CONSTRAINT PK_LTT PRIMARY KEY(MALOAITIEN)

--KHÓA CHÍNH CHO BẢNG TÀI KHOẢN---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT PK_TK PRIMARY KEY(MATK)



-------------------RÀNG BUỘC KHÓA NGOẠI-------------------



-------------------RÀNG BUỘC DUY NHẤT-------------------

---CCCD KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG 
ADD CONSTRAINT CCCD_KH UNIQUE(CCCD)

---SDT KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT SDT_KH UNIQUE(SDT)

---EMAIL KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT EMAIL_KH UNIQUE(EMAIL)

---SỐ TÀI KHOẢN LÀ DUY NHẤT---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT SOTAIKHOAN_TK UNIQUE(SOTAIKHOAN)



-------------------RÀNG BUỘC MIỀN GIÁ TRỊ-------------------

---GIỚI TÍNH NAM/NỮ CHO KHÁCH HÀNG---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_GTKH CHECK(GIOITINH = N'NAM' OR GIOITINH = N'NỮ')



-------------------RÀNG BUỘC MẶC ĐỊNH-------------------

---MẶC ĐỊNH SỐ DƯ CHO TAIKHOAN---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT DF_SODU DEFAULT 0 FOR SODU