USE master

--CREATE DATABASE QUAN LY NGAN HANG
GO 
CREATE DATABASE QLNH
--DROP DATABASE QLNH
GO
USE QLNH

-------------------TẠO BẢNG CHO CƠ SỞ DỮ LIỆU-------------------
GO
----Bang nhan vien (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE NHANVIEN(MANV CHAR(10) NOT NULL,
						TENNV NVARCHAR(30),
						GIOITINH NVARCHAR(5),
						NGAYSINH DATE,
						CHUC NVARCHAR(50),
						LUONG FLOAT,
						DIACHI NVARCHAR(50),
						SDT INT,
						MAPB INT,
						MACN CHAR(10))
GO
----Bang phong ban (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE PHONGBAN(MAPB INT NOT NULL,
						TENPB NVARCHAR(15))
GO
----Bang chi nhanh (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE CHINHANH(MACN CHAR(10) NOT NULL,
						TENCN NVARCHAR(50),
						DIACHICN NVARCHAR(50),
						SDTCN INT)
GO 
----Bang noi quy (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE NOIQUY(MANQ CHAR(10) NOT NULL,
					TIEUDE NVARCHAR(100),
					MOTA NVARCHAR(100),
					NGAYBH DATE,
					LOAIAPDUNG NVARCHAR(225))
GO
----Bang vi pham (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE VIPHAM(MAVP CHAR(10) NOT NULL,
					MANQ CHAR(10),
					MANV CHAR(10),
					MAKH CHAR(10),
					NGAYVP DATE,
					MOTAVP NVARCHAR(100),
					HINHTHUCXL NVARCHAR(100),
					TRANGTHAIXL NVARCHAR(100))

---BẢNG KHÁCH HÀNG (LÊ NGUYÊN VĨ)
--CCCD VÀ SDT NÊN SỬ DỤNG VARCHAR VÌ NÓ CÓ THỂ CHỨA KÝ TỰ BẮT ĐẦU BẰNG SỐ 0 CÒN KIỂU INT THÌ SẼ BỎ MẤT SỐ 0 Ở ĐẦU (VARCHAR:0384629483, INT:384629483)
GO
CREATE TABLE KHACHHANG(MAKH CHAR(10) NOT NULL,
						TENKH NVARCHAR(70),
						GIOITINH NVARCHAR,
						CCCD VARCHAR(12),
						SDT VARCHAR(10),
						EMAIL NVARCHAR(100),
						DIACHI NVARCHAR(100),
						QUOCTICH NVARCHAR(20),
						DOITUONG NVARCHAR,
						NGAYTAO DATETIME)

---BẢNG LOẠI TÀI KHOẢN (LÊ NGUYÊN VĨ)
GO
CREATE TABLE LOAITAIKHOAN(MALOAITK VARCHAR(10) NOT NULL,
							CHITIET NVARCHAR(30))

---BẢNG LOẠI TIỀN TỆ (LÊ NGUYÊN VĨ)
GO
CREATE TABLE LOAITIEN(MALOAITIEN VARCHAR(10) NOT NULL,
						TENLOAITIEN NVARCHAR(50),
						KYHIEU NVARCHAR,
						QUOCGIA NVARCHAR,
						TRANGTHAI NVARCHAR)

---BẢNG TÀI KHOẢN (LÊ NGUYÊN VĨ)
GO
CREATE TABLE TAIKHOAN(MATK CHAR(10) NOT NULL,
							MAKH CHAR(10),
							SOTAIKHOAN VARCHAR,
							MALOAITK VARCHAR(10),
							SODU DECIMAL,
							MALOAITIEN VARCHAR(10),
							NGAYMOTK DATETIME,
							TRANGTHAI NVARCHAR)

---BẢNG GIAO DỊCH (LÊ NGUYÊN VĨ)
GO
CREATE TABLE GIAODICH(MAGD CHAR(10) NOT NULL,
						MATK CHAR(10),
						LOAIGD NVARCHAR(25),
						SOTIEN DECIMAL,
						THOIGIANGD DATETIME,
						MOTA NVARCHAR(100),
						TRANGTHAI NVARCHAR)

---BẢNG BIÊN LAI (LÊ NGUÊN VĨ)
GO
CREATE TABLE BIENLAI(MABL CHAR(10) NOT NULL,
						MAGD CHAR(10),
						MAKH CHAR(10),
						MATK CHAR(10),
						MANV CHAR(10),
						SOTIEN DECIMAL,
						MALOAITIEN CHAR(10),
						LOAIBL NVARCHAR(30),
						MOTA NVARCHAR(100),
						TRANGTHAI NVARCHAR)
					


-------------------RÀNG BUỘC KHÓA CHÍNH-------------------
GO
--KHOA CHINH NHANVIEN (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NV PRIMARY KEY(MANV)
GO
--KHOA CHINH PHONG BAN (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE PHONGBAN
ADD CONSTRAINT PK_PB PRIMARY KEY(MAPB)
GO
--KHOA CHINH CHI NHANH (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE CHINHANH
ADD CONSTRAINT PK_CN PRIMARY KEY(MACN)
GO
--KHOA CHINH NOI QUY (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE NOIQUY
ADD CONSTRAINT PK_NQ PRIMARY KEY(MANQ)
GO
--KHOA CHINH VI PHAM (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE VIPHAM
ADD CONSTRAINT PK_VP PRIMARY KEY(MAVP)


------LÊ NGUYÊN VĨ------
---KHÓA CHÍNH CHO BẢNG KHÁCH HÀNG---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KH PRIMARY KEY(MAKH)

---KHÓA CHÍNH CHO BẢNG LOẠI TÀI KHOẢN---
GO
ALTER TABLE LOAITAIKHOAN
ADD CONSTRAINT PK_LTK PRIMARY KEY(MALOAITK)

--KHÓA CHÍNH CHO BẢNG LOẠI TIỀN TỆ---
GO
ALTER TABLE LOAITIEN
ADD CONSTRAINT PK_LTT PRIMARY KEY(MALOAITIEN)

--KHÓA CHÍNH CHO BẢNG TÀI KHOẢN---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT PK_TK PRIMARY KEY(MATK)

--KHÓA CHÍNH CHO BẢNG GIAO DỊCH---
GO
ALTER TABLE GIAODICH
ADD CONSTRAINT PK_GD PRIMARY KEY(MAGD)

--KHÓA CHÍNH CHO BẢNG BIÊN LAI---
GO
ALTER TABLE BIENLAI
ADD CONSTRAINT PK_BL PRIMARY KEY(MABL)



-------------------RÀNG BUỘC KHÓA NGOẠI-------------------



-------------------RÀNG BUỘC DUY NHẤT-------------------

------LÊ NGUYÊN VĨ------
---CCCD KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG 
ADD CONSTRAINT CCCD_KH UNIQUE(CCCD)

---SDT KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT SDT_KH UNIQUE(SDT)

---EMAIL KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT EMAIL_KH UNIQUE(EMAIL)

---SỐ TÀI KHOẢN LÀ DUY NHẤT---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT SOTAIKHOAN_TK UNIQUE(SOTAIKHOAN)



-------------------RÀNG BUỘC MIỀN GIÁ TRỊ-------------------

------LÊ NGUYÊN VĨ------
---GIỚI TÍNH NAM/NỮ CHO KHÁCH HÀNG---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_GTKH CHECK(GIOITINH = N'NAM' OR GIOITINH = N'NỮ')

---TRẠNG THÁI CHO BIÊN LAI---
GO
ALTER TABLE BIENLAI
ADD CONSTRAINT CK_TTBL CHECK(TRANGTHAI = N'ĐÃ IN' OR TRANGTHAI = N'CHƯA IN')



-------------------RÀNG BUỘC MẶC ĐỊNH-------------------

------LÊ NGUYÊN VĨ------
---MẶC ĐỊNH SỐ DƯ CHO TAIKHOAN---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT DF_SODU DEFAULT 0 FOR SODU