use master

CREATE DATABASE QLNH

GO
USE QLNH
-- DROP DATABSE QLNH
----------------Tao table
GO
----Bang nhan vien (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE NHANVIEN(MANV CHAR(10) NOT NULL,
						TENNV NVARCHAR(30),
						GIOITINH NVARCHAR(5),
						NGAYSINH DATE,
						CHUC NVARCHAR(50),
						LUONG FLOAT,
						DIACHI NVARCHAR(50),
						SDT INT,
						MAPB INT,
						MACN CHAR(10))
GO
----Bang phong ban (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE PHONGBAN(MAPB INT NOT NULL,
						TENPB NVARCHAR(15))
GO
----Bang chi nhanh (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE CHINHANH(MACN CHAR(10) NOT NULL,
						TENCN NVARCHAR(50),
						DIACHICN NVARCHAR(50),
						SDTCN INT)
GO 
----Bang noi quy (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE NOIQUY(MANQ CHAR(10) NOT NULL,
					TIEUDE NVARCHAR(100),
					MOTA NVARCHAR(100),
					NGAYBH DATE,
					LOAIAPDUNG NVARCHAR(225))
GO
----Bang vi pham (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE VIPHAM(MAVP CHAR(10) NOT NULL,
					MANQ CHAR(10),
					MANV CHAR(10),
					MAKH CHAR(10),
					NGAYVP DATE,
					MOTAVP NVARCHAR(100),
					HINHTHUCXL NVARCHAR(100),
					TRANGTHAIXL NVARCHAR(100))
-----RANG BUOC KHOA CHINH
GO
--KHOA CHINH NHANVIEN (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NV PRIMARY KEY(MANV)
GO
--KHOA CHINH PHONG BAN (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE PHONGBAN
ADD CONSTRAINT PK_PB PRIMARY KEY(MAPB)
GO
--KHOA CHINH CHI NHANH (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE CHINHANH
ADD CONSTRAINT PK_CN PRIMARY KEY(MACN)
GO
--KHOA CHINH NOI QUY (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE NOIQUY
ADD CONSTRAINT PK_NQ PRIMARY KEY(MANQ)
GO
--KHOA CHINH VI PHAM (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE VIPHAM
ADD CONSTRAINT PK_VP PRIMARY KEY(MAVP)
