USE master

--CREATE DATABASE QUAN LY NGAN HANG
GO 
CREATE DATABASE QLNH
--DROP DATABASE QLNH
--DROP TABLE
GO
USE QLNH

-------------------TẠO BẢNG CHO CƠ SỞ DỮ LIỆU-------------------
GO
----Bang nhan vien (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE NHANVIEN(MANV CHAR(10) NOT NULL,
						TENNV NVARCHAR(30),
						GIOITINH NVARCHAR(5),
						NGAYSINH DATE,
						CHUC NVARCHAR(50),
						LUONG FLOAT,
						DIACHI NVARCHAR(50),
						SDT INT,
						MAPB INT,
						MACN CHAR(10))
GO
----Bang phong ban (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE PHONGBAN(MAPB INT NOT NULL,
						TENPB NVARCHAR(15))
GO
----Bang chi nhanh (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE CHINHANH(MACN CHAR(10) NOT NULL,
						TENCN NVARCHAR(50),
						DIACHICN NVARCHAR(50),
						SDTCN INT)
GO 
----Bang noi quy (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE NOIQUY(MANQ CHAR(10) NOT NULL,
					TIEUDE NVARCHAR(100),
					MOTA NVARCHAR(100),
					NGAYBH DATE,
					LOAIAPDUNG NVARCHAR(225))
GO
----Bang vi pham (NGUYỄN KHÁNH ĐĂNG)
CREATE TABLE VIPHAM(MAVP CHAR(10) NOT NULL,
					MANQ CHAR(10),
					MANV CHAR(10),
					MAKH CHAR(10),
					NGAYVP DATE,
					MOTAVP NVARCHAR(100),
					HINHTHUCXL NVARCHAR(100),
					TRANGTHAIXL NVARCHAR(100))

---BẢNG KHÁCH HÀNG (LÊ NGUYÊN VĨ)
--CCCD VÀ SDT NÊN SỬ DỤNG VARCHAR VÌ NÓ CÓ THỂ CHỨA KÝ TỰ BẮT ĐẦU BẰNG SỐ 0 CÒN KIỂU INT THÌ SẼ BỎ MẤT SỐ 0 Ở ĐẦU (VARCHAR:0384629483, INT:384629483)
GO
CREATE TABLE KHACHHANG(MAKH CHAR(10) NOT NULL,
						TENKH NVARCHAR(70),
						GIOITINH NVARCHAR(10),
						CCCD VARCHAR(12),
						SDT VARCHAR(10),
						EMAIL NVARCHAR(100),
						DIACHI NVARCHAR(100),
						QUOCTICH NVARCHAR(20),
						DOITUONG NVARCHAR(20),
						NGAYTAO DATETIME)

---BẢNG LOẠI TÀI KHOẢN (LÊ NGUYÊN VĨ)
GO
CREATE TABLE LOAITAIKHOAN(MALOAITK VARCHAR(10) NOT NULL,
							CHITIET NVARCHAR(30))

---BẢNG LOẠI TIỀN TỆ (LÊ NGUYÊN VĨ)
GO
CREATE TABLE LOAITIEN(MALOAITIEN VARCHAR(10) NOT NULL,
						TENLOAITIEN NVARCHAR(50),
						KYHIEU NVARCHAR(10),
						QUOCGIA NVARCHAR(20),
						TRANGTHAI NVARCHAR(20))

---BẢNG TÀI KHOẢN (LÊ NGUYÊN VĨ)
GO
CREATE TABLE TAIKHOAN(MATK CHAR(10) NOT NULL,
							MAKH CHAR(10),
							SOTAIKHOAN VARCHAR(10),
							MALOAITK VARCHAR(10),
							SODU DECIMAL,
							MALOAITIEN VARCHAR(10),
							NGAYMOTK DATETIME,
							TRANGTHAI NVARCHAR(20))

---BẢNG GIAO DỊCH (LÊ NGUYÊN VĨ)
GO
CREATE TABLE GIAODICH(MAGD CHAR(10) NOT NULL,
						MATK CHAR(10),
						LOAIGD NVARCHAR(25),
						SOTIEN DECIMAL,
						THOIGIANGD DATETIME,
						MOTA NVARCHAR(100),
						TRANGTHAI NVARCHAR(20))

---BẢNG BIÊN LAI (LÊ NGUÊN VĨ)
GO
CREATE TABLE BIENLAI(MABL CHAR(10) NOT NULL,
						MAGD CHAR(10),
						MAKH CHAR(10),
						MATK CHAR(10),
						MANV CHAR(10),
						SOTIEN DECIMAL,
						MALOAITIEN CHAR(10),
						LOAIBL NVARCHAR(30),
						MOTA NVARCHAR(100),
						TRANGTHAI NVARCHAR(20))				
GO
---BANG CHUYEN KHOAN
CREATE TABLE CHUYENKHOAN(MACK CHAR(10) NOT NULL, 
						NGAYCK DATETIME, 
						SOTIEN DECIMAL, 
						MATKGUI CHAR(10), 
						MATKNHAN CHAR(10), 
						NOIDUNG NVARCHAR(250))
GO
---BANG KHOAN VAY
CREATE TABLE KHOANVAY(MAVAY CHAR(10) NOT NULL, 
						SOTIENVAY DECIMAL,
						TONGTIEN DECIMAL,
						TIENTHANG DECIMAL,
						NGAYVAY DATETIME, 
						THOIHAN DATETIME,
						SOTHANG DECIMAL,
						TRANGTHAI NVARCHAR(50), 
						MAKH CHAR(10), 
						MALAISUAT CHAR(10))
GO
---BANG LAI SUAT
CREATE TABLE LAISUAT(MALAISUAT CHAR(10) NOT NULL, 
						TENLOAIVAY NVARCHAR(250), 
						LAISUAT DECIMAL,
						KIEULAI NVARCHAR(50))
GO
---BANG LICH SU TRA NO
CREATE TABLE LICHSUTRANO(MALICHSU CHAR(10) NOT NULL,
						MAVAY CHAR(10),
						SOTIENGOC DECIMAL,
						SOTIENTRA DECIMAL,
						NGAYTRA DATETIME)
GO
--BANG KHUYEN MAI
CREATE TABLE KHUYENMAI(MAKM CHAR(10) NOT NULL, 
						TENKM NVARCHAR(250), 
						MOTA NVARCHAR(250), 
						NGAYBD DATETIME, 
						NGAYKT DATETIME, 
						DKAPDUNG NVARCHAR(250))
GO
--BANG AP DUNG KHUYEN MAI
CREATE TABLE APDUNGKHUYENMAI(MAKM CHAR(10) NOT NULL, 
						MAKH CHAR(10) NOT NULL, 
						MATK CHAR(10), 
						NGAYAPDUNG DATETIME)
GO

--BANG LOGIN
CREATE TABLE DANGNHAP(MADN CHAR(20) NOT NULL,
					PASS CHAR(50),
					QUYEN NVARCHAR(50),
					MANV CHAR(10))


-------------------RÀNG BUỘC KHÓA CHÍNH-------------------
GO
--KHOA CHINH NHANVIEN (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE NHANVIEN
ADD CONSTRAINT PK_NV PRIMARY KEY(MANV)
GO
--KHOA CHINH PHONG BAN (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE PHONGBAN
ADD CONSTRAINT PK_PB PRIMARY KEY(MAPB)
GO
--KHOA CHINH CHI NHANH (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE CHINHANH
ADD CONSTRAINT PK_CN PRIMARY KEY(MACN)
GO
--KHOA CHINH NOI QUY (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE NOIQUY
ADD CONSTRAINT PK_NQ PRIMARY KEY(MANQ)
GO
--KHOA CHINH VI PHAM (NGUYỄN KHÁNH ĐĂNG)
ALTER TABLE VIPHAM
ADD CONSTRAINT PK_VP PRIMARY KEY(MAVP)


------LÊ NGUYÊN VĨ------
---KHÓA CHÍNH CHO BẢNG KHÁCH HÀNG---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT PK_KH PRIMARY KEY(MAKH)

---KHÓA CHÍNH CHO BẢNG LOẠI TÀI KHOẢN---
GO
ALTER TABLE LOAITAIKHOAN
ADD CONSTRAINT PK_LTK PRIMARY KEY(MALOAITK)

--KHÓA CHÍNH CHO BẢNG LOẠI TIỀN TỆ---
GO
ALTER TABLE LOAITIEN
ADD CONSTRAINT PK_LTT PRIMARY KEY(MALOAITIEN)

--KHÓA CHÍNH CHO BẢNG TÀI KHOẢN---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT PK_TK PRIMARY KEY(MATK)

--KHÓA CHÍNH CHO BẢNG GIAO DỊCH---
GO
ALTER TABLE GIAODICH
ADD CONSTRAINT PK_GD PRIMARY KEY(MAGD)

--KHÓA CHÍNH CHO BẢNG BIÊN LAI---
GO
ALTER TABLE BIENLAI
ADD CONSTRAINT PK_BL PRIMARY KEY(MABL)



--KHOA CHINH CHO BANG CHUYEN KHOAN
GO
ALTER TABLE CHUYENKHOAN
ADD CONSTRAINT PK_CK PRIMARY KEY(MACK)

--KHOA CHINH CHO BANG KHOAN VAY
GO
ALTER TABLE KHOANVAY
ADD CONSTRAINT PK_KV PRIMARY KEY(MAVAY)

--KHOA CHINH CHO BANG LAI SUAT
GO
ALTER TABLE LAISUAT
ADD CONSTRAINT PK_LS PRIMARY KEY(MALAISUAT)

--KHOA CHINH CHO BANG LICH SU TRA NO
GO
ALTER TABLE LICHSUTRANO
ADD CONSTRAINT PK_LSTN PRIMARY KEY(MALICHSU)

--KHOA CHINH CHO BANG KHUYEN MAI
GO
ALTER TABLE KHUYENMAI
ADD CONSTRAINT PK_KM PRIMARY KEY(MAKM)

--KHOA CHINH CHO BANG AP DUNG KHUYEN MAI
GO
ALTER TABLE APDUNGKHUYENMAI
ADD CONSTRAINT PK_ADKM PRIMARY KEY(MAKM,MAKH)

--KHOA CHINH CHO LOGIN
GO
ALTER TABLE DANGNHAP
ADD CONSTRAINT PK_LG PRIMARY KEY(MADN)


-------------------RÀNG BUỘC KHÓA NGOẠI-------------------
---NHAN VIEN VOI PHONG BAN
GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_PB FOREIGN KEY(MAPB)
REFERENCES PHONGBAN(MAPB)

---NHAN VIEN VOI CHI NHANH
GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT FK_NV_CN FOREIGN KEY(MACN)
REFERENCES CHINHANH(MACN)

-- LOGIN VỚI NHÂNVIEN
ALTER TABLE DANGNHAP
ADD CONSTRAINT FK_DN_NV FOREIGN KEY (MANV)
REFERENCES NHANVIEN(MANV)
GO

---BIEN LAI VOI NHAN VIEN
GO
ALTER TABLE BIENLAI
ADD CONSTRAINT FK_BL_NV FOREIGN KEY(MANV)
REFERENCES NHANVIEN(MANV)

---BIEN LAI VOI KHACH HANG
GO
ALTER TABLE BIENLAI
ADD CONSTRAINT FK_BL_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---TAI KHOAN VOI KHACH HANG
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_TK_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---TAI KHOAN VOI LOAI TAI KHOAN
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_TK_LTK FOREIGN KEY(MALOAITK)
REFERENCES LOAITAIKHOAN(MALOAITK)


---TAI KHOAN VOI LOAI TIEN
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT FK_TK_LT FOREIGN KEY(MALOAITIEN)
REFERENCES LOAITIEN(MALOAITIEN)

---CHUYEN KHOAN VOI LOAI TAI KHOAN
GO
ALTER TABLE CHUYENKHOAN
ADD CONSTRAINT FK_CKG_TK FOREIGN KEY(MATKGUI)
REFERENCES TAIKHOAN(MATK)

---CHUYEN KHOAN VOI LOAI TAI KHOAN
GO
ALTER TABLE CHUYENKHOAN
ADD CONSTRAINT FK_CKN_TK FOREIGN KEY(MATKNHAN)
REFERENCES TAIKHOAN(MATK)

---KHOAN VAY VOI KHACH HANG
GO
ALTER TABLE KHOANVAY
ADD CONSTRAINT FK_KV_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---KHOAN VAY VOI LAI SUAT
GO
ALTER TABLE KHOANVAY
ADD CONSTRAINT FK_KV_LS FOREIGN KEY(MALAISUAT)
REFERENCES LAISUAT(MALAISUAT)

---LICH SU TRA NO VOI LOAI KHOAN VAY
GO
ALTER TABLE LICHSUTRANO
ADD CONSTRAINT FK_LSTN_KV FOREIGN KEY(MAVAY)
REFERENCES KHOANVAY(MAVAY)

---AP DUNG KHUYEN MAI VOI KHUYEN MAI
GO
ALTER TABLE APDUNGKHUYENMAI
ADD CONSTRAINT FK_ADKM_KM FOREIGN KEY(MAKM)
REFERENCES KHUYENMAI(MAKM)

---AP DUNG KHUYEN MAI VOI KHACH HANG
GO
ALTER TABLE APDUNGKHUYENMAI
ADD CONSTRAINT FK_ADKM_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---AP DUNG KHUYEN MAI VOI TAI KHOAN
GO
ALTER TABLE APDUNGKHUYENMAI
ADD CONSTRAINT FK_ADKM_TK FOREIGN KEY(MATK)
REFERENCES TAIKHOAN(MATK)

---VI PHAM VOI NOI QUY
GO
ALTER TABLE VIPHAM
ADD CONSTRAINT FK_VP_NQ FOREIGN KEY(MANQ)
REFERENCES NOIQUY(MANQ)

---VI PHAM VOI NHAN VIEN
GO
ALTER TABLE VIPHAM
ADD CONSTRAINT FK_VP_NV FOREIGN KEY(MANV)
REFERENCES NHANVIEN(MANV)

---VI PHAM VOI KHACH HANG
GO
ALTER TABLE VIPHAM
ADD CONSTRAINT FK_VP_KH FOREIGN KEY(MAKH)
REFERENCES KHACHHANG(MAKH)

---GIAO DICH VOI TAI KHOAN
GO
ALTER TABLE GIAODICH
ADD CONSTRAINT FK_GD_TK FOREIGN KEY(MATK)
REFERENCES TAIKHOAN(MATK)

-------------------RÀNG BUỘC DUY NHẤT-------------------

-----NGUYỄN KHÁNH ĐĂNG-----
---SDT NHAN VIEN LA DUY NHAT---
GO
ALTER TABLE NHANVIEN
ADD CONSTRAINT SDT_NV UNIQUE(SDT)
---TEN PHONG BAN LA DUY NHAT---
GO 
ALTER TABLE PHONGBAN
ADD CONSTRAINT TENPB_PB UNIQUE(TENPB)
---TEN CHI NHANH LA DUY NHAT---
GO
ALTER TABLE CHINHANH
ADD CONSTRAINT TENCN_CN UNIQUE(TENCN)
---SDT CHI NHANH LA DUY NHAT---
GO
ALTER TABLE CHINHANH
ADD CONSTRAINT SDTCN_CN UNIQUE(SDTCN)

------LÊ NGUYÊN VĨ------
---CCCD KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG 
ADD CONSTRAINT CCCD_KH UNIQUE(CCCD)

---SDT KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT SDT_KH UNIQUE(SDT)

---EMAIL KHÁCH HÀNG LÀ DUY NHẤT---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT EMAIL_KH UNIQUE(EMAIL)

---SỐ TÀI KHOẢN LÀ DUY NHẤT---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT SOTAIKHOAN_TK UNIQUE(SOTAIKHOAN)


GO
ALTER TABLE DANGNHAP ADD CONSTRAINT UQ_LG_MANV UNIQUE (MANV)



-------------------RÀNG BUỘC MIỀN GIÁ TRỊ-------------------

-----NGUYỄN KHÁNH ĐĂNG-----
---GIOI TINH CHO NHAN VIEN---
GO 
ALTER TABLE NHANVIEN
ADD CONSTRAINT CK_GTNV CHECK(GIOITINH = N'NAM' OR GIOITINH = N'NỮ')
---TRANG THAI XU LY VI PHAM NHAN VIEN---
GO
ALTER TABLE VIPHAM
ADD CONSTRAINT CK_TTXL CHECK(TRANGTHAIXL = N'ĐÃ XỬ LÝ' OR TRANGTHAIXL = N'CHƯA XỬ LÝ')

------LÊ NGUYÊN VĨ------
---GIỚI TÍNH NAM/NỮ CHO KHÁCH HÀNG---
GO
ALTER TABLE KHACHHANG
ADD CONSTRAINT CK_GTKH CHECK(GIOITINH = N'NAM' OR GIOITINH = N'NỮ')

---TRẠNG THÁI CHO BIÊN LAI---
GO
ALTER TABLE BIENLAI
ADD CONSTRAINT CK_TTBL CHECK(TRANGTHAI = N'ĐÃ IN' OR TRANGTHAI = N'CHƯA IN')

---NGAY KET THUC CHO KHUYEN MAI
GO
ALTER TABLE KHUYENMAI
ADD CONSTRAINT CK_NKT
CHECK (NGAYKT >= NGAYBD);

-------------------RÀNG BUỘC MẶC ĐỊNH-------------------

------LÊ NGUYÊN VĨ------
---MẶC ĐỊNH SỐ DƯ CHO TAIKHOAN---
GO
ALTER TABLE TAIKHOAN
ADD CONSTRAINT DF_SODU DEFAULT 0 FOR SODU
